from __future__ import annotations

import ipaddress
import uuid
from collections.abc import Iterable
from datetime import date
from hashlib import blake2s
from typing import Any
from urllib.parse import urlsplit

import yaml
from sigma.collection import SigmaCollection

from app.models import IOC, IOCType, RuleType

REVIEW_NOTICE = (
    "AUTO-GENERATED by ThreatMesh; human review and environment-specific tuning required."
)
DEMO_NOTICE = "SYNTHETIC DEMO ONLY; not live threat intelligence or production detection content."

SOURCE_REFERENCES = {
    "feodo": "https://feodotracker.abuse.ch/",
    "threatfox": "https://threatfox.abuse.ch/",
    "urlhaus": "https://urlhaus.abuse.ch/",
}


def _suricata_escape(value: str) -> str:
    # Feed labels and indicator values are untrusted. Suricata rule options are
    # line-oriented, so controls must never reach the rendered rule.
    printable = "".join(character if character.isprintable() else " " for character in value)
    return printable.replace("\\", "\\\\").replace('"', '\\"').replace(";", "\\;")


def detection_key(ioc: IOC) -> str:
    """Return the canonical, feed-independent identity of a detection target."""

    return f"{ioc.ioc_type.value}:{ioc.indicator_key}"


def detection_uuid(ioc: IOC) -> uuid.UUID:
    return uuid.uuid5(uuid.NAMESPACE_URL, f"threatmesh:detection:{detection_key(ioc)}")


def suricata_sid(ioc: IOC) -> int:
    """Build a stable local SID from the complete semantic detection identity."""

    digest = blake2s(f"threatmesh:suricata:{detection_key(ioc)}".encode(), digest_size=4).digest()
    # SIDs below 1,000,000 are reserved. Keep the result within signed 32-bit range
    # for broad rules-engine/tooling compatibility.
    return 1_000_000 + int.from_bytes(digest) % (2_147_483_647 - 1_000_000)


def artifact_filename(detection_identity: str, rule_type: RuleType) -> str:
    """Return a filesystem-safe filename that is stable across database rebuilds."""

    artifact_id = uuid.uuid5(uuid.NAMESPACE_URL, f"threatmesh:detection:{detection_identity}")
    extension = "yml" if rule_type is RuleType.SIGMA else "rules"
    return f"threatmesh-{rule_type.value}-{artifact_id}.{extension}"


def _sources(values: Iterable[str] | None, fallback: str) -> list[str]:
    return sorted({value.strip().lower() for value in (values or [fallback]) if value.strip()})


def _source_references(sources: Iterable[str]) -> list[str]:
    return [SOURCE_REFERENCES[source] for source in sources if source in SOURCE_REFERENCES]


def confidence_level(confidence: float | None) -> str:
    score = confidence or 0
    if score >= 70:
        return "high"
    if score >= 40:
        return "medium"
    return "low"


def _host_match(host: str) -> str:
    escaped = _suricata_escape(host)
    try:
        ipaddress.ip_address(host)
    except ValueError:
        # dotprefix prepends a virtual dot to the inspected buffer. Combined with
        # a dot-prefixed content and endswith, this matches example.com and its
        # subdomains, but not the suffix collision notexample.com.
        return f'content:".{escaped}"; dotprefix; nocase; endswith;'
    return f'content:"{escaped}"; startswith; endswith;'


def generate_suricata(
    ioc: IOC, *, corroborating_sources: Iterable[str] | None = None
) -> str | None:
    family = _suricata_escape(ioc.malware_family or "unattributed threat")
    message = f"ThreatMesh known IOC - {family}"
    sid = suricata_sid(ioc)
    sources = _sources(corroborating_sources, ioc.source_feed)
    metadata = (
        "metadata: former_category MALWARE, confidence "
        f"{round(ioc.confidence_score or 0)}, source_count {len(sources)}"
    )
    evidence = f"# Corroborating sources: {', '.join(sources)}\n"
    provenance = f"# {DEMO_NOTICE}\n" if ioc.is_demo else ""
    if ioc.ioc_type is IOCType.IP:
        try:
            address = ipaddress.ip_address(ioc.ioc_value)
        except ValueError:
            return None
        protocol = "ipv6" if address.version == 6 else "ip"
        destination_port = str(ioc.port) if ioc.port else "any"
        return (
            f"# {REVIEW_NOTICE}\n"
            f"{provenance}"
            f"{evidence}"
            f'alert {protocol} any any -> {address} {destination_port} (msg:"{message}"; '
            f"{metadata}; sid:{sid}; rev:1;)"
        )
    if ioc.ioc_type is IOCType.DOMAIN:
        domain_match = _host_match(ioc.ioc_value)
        return (
            f"# {REVIEW_NOTICE}\n"
            f"{provenance}"
            f"{evidence}"
            f'alert dns any any -> any any (msg:"{message}"; dns.query; '
            f"{domain_match} {metadata}; sid:{sid}; rev:1;)"
        )
    if ioc.ioc_type is IOCType.URL:
        parsed = urlsplit(ioc.ioc_value)
        host = parsed.hostname or ""
        path = _suricata_escape(parsed.path or "/")
        if not host:
            return None
        destination_port = parsed.port or (443 if parsed.scheme.lower() == "https" else 80)
        host_match = _host_match(host)
        if parsed.scheme.lower() == "https":
            try:
                address = ipaddress.ip_address(host)
            except ValueError:
                target = "any"
                inspection = f"tls.sni; {host_match} "
            else:
                target = str(address)
                inspection = ""
            return (
                f"# {REVIEW_NOTICE}\n"
                f"{provenance}"
                f"{evidence}"
                f'alert tls any any -> {target} {destination_port} (msg:"{message}"; '
                f"{inspection}{metadata}; sid:{sid}; rev:1;)"
            )
        return (
            f"# {REVIEW_NOTICE}\n"
            f"{provenance}"
            f"{evidence}"
            f'alert http any any -> any {destination_port} (msg:"{message}"; http.host; '
            f'{host_match} http.uri; content:"{path}"; startswith; '
            f"{metadata}; sid:{sid}; rev:1;)"
        )
    return None


def _sigma_field(ioc: IOC) -> tuple[str, str] | None:
    if ioc.ioc_type is IOCType.IP:
        return "DestinationIp", ioc.ioc_value
    if ioc.ioc_type is IOCType.DOMAIN:
        return "query", ioc.ioc_value
    if ioc.ioc_type is IOCType.URL:
        return "url", ioc.ioc_value
    if ioc.ioc_type is IOCType.HASH:
        length_to_field = {32: "md5", 40: "sha1", 64: "sha256"}
        return length_to_field.get(len(ioc.ioc_value), "hash"), ioc.ioc_value
    return None


def generate_sigma(
    ioc: IOC,
    *,
    corroborating_sources: Iterable[str] | None = None,
    technique_ids: Iterable[str] | None = None,
) -> str | None:
    field = _sigma_field(ioc)
    if field is None:
        return None
    sources = _sources(corroborating_sources, ioc.source_feed)
    tags = ["tlp.white"]
    techniques = sorted(set(technique_ids or ioc.attack_technique_ids or []))
    tags.extend(f"attack.{technique.lower()}" for technique in techniques)
    selection: dict[str, Any] = {field[0]: field[1]}
    if ioc.ioc_type is IOCType.IP and ioc.port:
        selection["DestinationPort"] = ioc.port
    document: dict[str, Any] = {
        "title": f"ThreatMesh IOC Match - {ioc.malware_family or ioc.ioc_type.value}",
        "id": str(detection_uuid(ioc)),
        "status": "experimental",
        "description": (f"{DEMO_NOTICE} " if ioc.is_demo else "")
        + f"{REVIEW_NOTICE} Corroborating sources: {', '.join(sources)}.",
        "author": "ThreatMesh",
        "date": date.today().isoformat(),
        "references": _source_references(sources),
        "tags": tags,
        "logsource": {"category": "network_connection"},
        "detection": {"selection": selection, "condition": "selection"},
        "falsepositives": ["Indicator reuse, sinkholes, or stale intelligence"],
        "level": confidence_level(ioc.confidence_score),
    }
    rendered = yaml.safe_dump(document, sort_keys=False, allow_unicode=True)
    # pySigma parses the emitted rule so malformed detection-as-code is never persisted.
    SigmaCollection.from_yaml(rendered)
    return rendered


def generate_rule(
    ioc: IOC,
    rule_type: RuleType,
    *,
    corroborating_sources: Iterable[str] | None = None,
    technique_ids: Iterable[str] | None = None,
) -> str | None:
    if rule_type is RuleType.SURICATA:
        return generate_suricata(ioc, corroborating_sources=corroborating_sources)
    return generate_sigma(
        ioc,
        corroborating_sources=corroborating_sources,
        technique_ids=technique_ids,
    )
